# Exemplo de docker-compose.yml (sem a linha "version")
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: >
        mongosh --quiet --eval "if(db.runCommand({ ping: 1 }).ok === 1){ exit 0 } else { exit 1 }"
      interval: 10s
      timeout: 5s
      retries: 5




  backend:
    build: ./backend
    container_name: cursos-flix-backend
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
      - CLIENT_URL=${CLIENT_URL}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: cursos-flix-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
